### ISSUE TITLE
训练过程遇到问题

### ISSUE THREAD

**Issue by EvelynCarter** [RuBP17/AlphaDou#3]
Traceback (most recent call last):
  File "/root/autodl-tmp/AlphaDou-main/douzero/dmc/utils.py", line 89, in act
    agent_output = model.forward(position, obs['z_batch'], obs['x_batch'], flags=flags)
  File "/root/autodl-tmp/AlphaDou-main/douzero/dmc/models.py", line 286, in forward
    return model.forward(z, x, training, flags)
  File "/root/autodl-tmp/AlphaDou-main/douzero/dmc/models.py", line 115, in forward
    elif flags is not None and flags.action_threshold > 0 and bombs:
AttributeError: 'Namespace' object has no attribute 'action_threshold'

**Comment by RuBP17** [comment]
This issue has been resolved. You can pull the code again.
